// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uigkpjvtipnfxyjijrtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZ2twanZ0aXBuZnh5amlqcnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTIzNjgsImV4cCI6MjA1OTU4ODM2OH0.hW267m7Cmtqq7gS0l5rQDtPdmN_KZk2P0Nac-TT1OeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);